[workspace]
members = [
    "core",
    "examples/log_features",
    "examples/serve_ml",
    "examples/spin",
    "filtergen",
]

[profile.release]
lto = true

[patch.crates-io]
pcap = { git = 'https://github.com/thegwan/pcap', branch = 'compile-optimized' }

